grafana:
    image: grafana/grafana
    ports:
        - "3000:3000"
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=vpn123
        - GF_INSTALL_PLUGINS=grafana-simple-json-datasource
    volumes:
        - $PWD/grafana:/var/lib/grafana